name = "RANSACVisualizer"
uuid = "d8b64869-c60f-5359-ae4c-f9741940db4e"
authors = ["Tamás Cserteg <csertegt@gmail.com>"]
version = "0.1.1"

[deps]
RANSAC = "d6bc97e0-a563-11e9-1861-c573f65f3bc3"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
